### ISSUE TITLE
can you please add firebase database support?

### ISSUE THREAD

**Issue by bsde1234** [cwellsx/view#7]
can you please add firebase database support?

**Comment by cwellsx** [comment]
I'd like to but I'm looking for employment at the moment so I'd need to do this in my spare time if at all -- so maybe not.

The first thing to do before adding firebase support was to support an external server i.e. not just a "mock server" embedded in the browser. I started that (built on top of express) and know how to do it. A complication is implementing server-side rendering efficiently without an additional framework like Next.js -- i.e. to implement the server's supplying data to the React code without the React code's using the in-browser `fetch` API -- that seems like a half a week or so of coding to complete.

After the standalone/separate server process exists, then it would be possible to implement any database backend[s] for it.

Why would you like Firebase instead of anything else, e.g. SQL or  MongoDB?

Anyway the latest (current) change that I made -- i.e. https://github.com/cwellsx/view/commit/8167acd3bea864307e3a361b521e1926a38bc9b5 -- might be enough of an infrastructure change to support beginning to implement support for Firebase. Before I made this change, the client-side API was implemented in client/src/api.ts and it used the browser's `fetch` API to get data from the server and/or from the mock server. I changed this so that the Api is now an abstract interface and is a dependency injected into the React application -- you can see this in there now being two different index files (named `index-client.ts` and `index-mock.ts`) in the ui-react/src directory.

If the time ever came to support firebase then this might be how and where to hook it into the application -- i.e. implement the abstract Api interface using Firebase, and write a `index-fire.ts` which instantiates that and injects it into the React app, what do you think?

**Comment by bsde1234** [comment]
Hi @cwellsx thanks for your reply. I am new to coding. During search in github, I come across this project and looks like a promising project. Even if I can't completely follow the details you specified, I am happy to know that you may consider firebase when you get time. Thank you.
